line_length:
- 200 # warning
- 300 # error

disabled_rules:
- force_cast
- identifier_name
- switch_case_alignment
- trailing_whitespace
- unused_optional_binding
- force_try

excluede:
- MovieAppTask/SceneDelegate.swift
